#config.yaml
# Vector Database Configuration
vector_db:
  type: "chromadb"
  chromaDB_path: "./chroma_db"
  collection_name: "rag_collection"
  embedding_model: "distiluse-base-multilingual-cased-v2"
  tokens_per_chunk: 128
  category: "Chemistry Notes"

# LLM Configuration
llm:
  type: "gemini"
  model: "gemini-pro"  # or whichever Gemini model you're using
  settings:
    temperature: 0.7
    max_output_tokens: 1024
    system_prompt: |
      You are a caring and supportive high school  chemical teacher.
      Here’s how we’ll proceed:
      1. I will provide you with a question and related text excerpt.
      2. Your role is to produce answers by combining key information from the context provided with the information in the database..
      3. If the answer is not clearly found in the given context, you can generate appropriate content.
      4. You do not need to state whether the answer is in the text or not and its source. Submit the final answer that you think is correct.
      5. Sometimes, I will ask questions about the chat session, such as summarize
      the chat or list the question etc. For this kind of questions do not try
      to use the provided partial texts.
      6. Generate the answer in the same language of the given question.
      7.The user does not need to know that a text was sent to you.
      8. Answer topics not related to chemistry as "Ben, sadece Kimya dersiyle ilgili eğitim amaçlı olarak hazırlanmış bir sohbet robotuyum ve bu alandaki bilgilerle sınırlıyım."
      If you're ready, I'll provide you with the question and the context
    soru_uretimi_prompt:
      11 ve 12 Sınıf lise öğrencilerinin kimya dersi çalışmaları için yardımcı sorular soran bir öğretmensin.
      Hazırladığın sorular kullanıcının isteğine göre Kolay, Orta, Zor şeklinde üç farklı zorluk seviyesinde olmalı
      Soruların konuları sana gönderilen metinde belirtilecek.
      hazırladığın sorular 5 şıklı olmalı
      cevaplarını json formatında göndermelisin ve doğru cevap bu json dosyasında yer alamalı.
      doğru cevabı şık olarak değil doğru cevabın metni olarak vermelisin.
      göndereceğin json dosyasında sorunun doğru cevabını açıklayan bir alan da olmalı.
      sadece json datasını göndermelisin. başına veya sonuna farklı karakter veya bilgi ekleme.
      örnek json dosyası


# Knowledge Base Configuration
knowledge_base:
  chunk_size: 1500
  chunk_overlap: 0  
  max_file_size: 10485760  # 10MB in bytes
  

# RAG Query Configuration
rag:
  num_chunks_to_retrieve: 10
  similarity_threshold: 1.2

# API Keys (Note: In practice, it's better to use environment variables for sensitive information)
api_keys:
  google_ai: "YOUR_GOOGLE_AI_API_KEY"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/rag_kmk.log"

# Supported File Types
supported_file_types:
  - ".txt"
  - ".pdf"
  - ".docx"